### PR TITLE
fix: update project name when performing soft delete

### LINKED ISSUE #20: After deleting a project cannot create with the same name.
Steps to Reproduce

- Deleted the project.
- Create it again with the same name.

### PR DESCRIPTION
**Pull request by sachdevavaibhav**
- [x] Fix: update project name when performing soft delete using timestamp so that the field remains unique.

Fixes #20

### CODE REVIEW

File: app/screens/Projects/ProjectListColumnConfig.tsx [hunk 1]
```diff
@@ -317,10 +317,12 @@ export const PROJECT_LIST_COLUMN_CONFIG: ColumnDef<IProjectItem>[] = [
 
       const handleConfirmDelete = async (event: React.MouseEvent) => {
         const projectId = row.original.projectId
+        const timestampString = new Date().toISOString()
+        const updatedName = `${row.original.projectName}_${timestampString}`
         const status = 'Archived'
 
         updateProjectStatus.submit(
-          {projectId, status},
+          {projectId, status, updatedName},
```
Comment (ashutoshd11) [inline app/screens/Projects/ProjectListColumnConfig.tsx:325]: Updated name should not be given from FE, this name should be derived at controller level and then send to dao, as this would not change the API contract for updating the project status, you can also change the status as `Deleted` from FE [i.e. in line 322] it would be fine.

**Review by ashutoshd11 — COMMENTED** [review]
Regarding current implementation I am not seeing any changes in `app/routes/api/v1/updateProjectStatus.ts` but there are changes in it's test file, this fix would not work as per current implementation because updatedName would be ignored.

**Comment by sachdevavaibhav** [comment]
@ashutoshd11 
I understood what I did wrong. I will be make changes in the controller and also need to make changes in DAO such that it  handles other status updates and soft delete as well. Will make the changes and push them.

File: app/dataController/projects.controller.ts [hunk 2]
```diff
@@ -26,15 +26,36 @@ export interface IArchiveProjects {
...
   getProjectInfo: (projectId: number) => ProjectsDao.getProjectInfo(projectId),
   createProject: (params: ICreateProject) => ProjectsDao.createProject(params),
   editProject: (params: IEditProject) => ProjectsDao.editProject(params),
-  updateProjectStatus: (params: IArchiveProjects) =>
-    ProjectsDao.updateProjectStatus(params),
+  updateProjectStatus: async (params: IArchiveProjects) => {
+    const {projectId, status} = params
+    if (status === 'Archived') {
+      const projectInfo = await ProjectsDao.getProjectInfo(projectId)
+      const project = projectInfo[0]
```
Comment (ashutoshd11) [inline app/dataController/projects.controller.ts:41]:
```suggestion
      const project = projectInfo?.[0]
```
adding this would save it from unknown error, below `if` block would handle it gracefully.

File: app/dataController/projects.controller.ts [hunk 3]
```diff
@@ -26,15 +26,36 @@ export interface IArchiveProjects {
...
 const ProjectsController = {
   getAllProjects: (params: IGetAllProjects) => ProjectsDao.getAll(params),
   getProjectInfo: (projectId: number) => ProjectsDao.getProjectInfo(projectId),
   createProject: (params: ICreateProject) => ProjectsDao.createProject(params),
   editProject: (params: IEditProject) => ProjectsDao.editProject(params),
-  updateProjectStatus: (params: IArchiveProjects) =>
-    ProjectsDao.updateProjectStatus(params),
+  updateProjectStatus: async (params: IArchiveProjects) => {
+    const {projectId, status} = params
+    if (status === 'Archived') {
```
Comment (ashutoshd11) [inline app/dataController/projects.controller.ts:39]:
```suggestion
    if (status === 'Archived' || status === 'Deleted') {
```
let's handle for both the cases

File: app/routes/api/v1/__tests__/updateProjectStatus.test.ts [hunk 4]
```diff
@@ -25,6 +25,7 @@ describe('Update Project Status - Action Function', () => {
     const requestData = {
       projectId: 123,
       status: 'Archived',
+      updatedName: 'Website_2025-02-28T12:01:12.807Z',
```
Comment (ashutoshd11) [inline app/routes/api/v1/__tests__/updateProjectStatus.test.ts:28]: This should be reverted now, as there is no changes at API level

File: app/screens/Projects/ProjectListColumnConfig.tsx [hunk 5]
```diff
@@ -317,10 +317,12 @@ export const PROJECT_LIST_COLUMN_CONFIG: ColumnDef<IProjectItem>[] = [
 
       const handleConfirmDelete = async (event: React.MouseEvent) => {
         const projectId = row.original.projectId
+        const timestampString = new Date().toISOString()
+        const updatedName = `${row.original.projectName}_${timestampString}`
         const status = 'Archived'
```
Comment (ashutoshd11) [inline app/screens/Projects/ProjectListColumnConfig.tsx:322]:
```suggestion
        const status = 'Deleted'
```
This could be done, and all other changes should be reverted of this file as no changes at FE level.

**Review by ashutoshd11 — APPROVED** [review]
